<a href="https://colab.research.google.com/github/18121a05l8/basics-of-tensorflow-1/blob/main/Creating_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from __future__ import absolute_import
from __future__ import print_function
from __future__ import division

import tensorflow as tf

In [ ]:
ten = tf.random.normal([2,3,4],2,1)
print(ten)

tf.Tensor(
[[[ 2.3591003   3.924478    1.9957986   1.5840237 ]
  [ 2.1052017   1.6462998   2.8093176   2.3065953 ]
  [ 3.0374813   2.8344321   1.8001952   1.1931461 ]]

 [[ 3.2624083   2.5387187   2.9646502   3.8290107 ]
  [ 1.8132234  -0.25027943  2.8257606   0.35598338]
  [ 2.1425831   1.4351314   1.5402347   2.1957223 ]]], shape=(2, 3, 4), dtype=float32)


In [ ]:
tf.multiply(ten,ten)

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[ 5.5653543 , 15.401528  ,  3.983212  ,  2.5091312 ],
        [ 4.4318743 ,  2.710303  ,  7.8922653 ,  5.320382  ],
        [ 9.226293  ,  8.034005  ,  3.2407029 ,  1.4235977 ]],

       [[10.643308  ,  6.4450927 ,  8.78915   , 14.661324  ],
        [ 3.2877789 ,  0.06263979,  7.984923  ,  0.12672417],
        [ 4.5906625 ,  2.0596023 ,  2.3723228 ,  4.8211966 ]]],
      dtype=float32)>

In [ ]:
tf.scalar_mul(2,ten)

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[ 4.7182007 ,  7.848956  ,  3.9915972 ,  3.1680474 ],
        [ 4.2104034 ,  3.2925997 ,  5.618635  ,  4.6131907 ],
        [ 6.0749626 ,  5.6688643 ,  3.6003904 ,  2.3862922 ]],

       [[ 6.5248165 ,  5.0774374 ,  5.9293003 ,  7.6580215 ],
        [ 3.6264467 , -0.50055885,  5.651521  ,  0.71196675],
        [ 4.2851663 ,  2.8702629 ,  3.0804694 ,  4.3914447 ]]],
      dtype=float32)>

In [ ]:
print(ten)
tf.abs(ten)

tf.Tensor(
[[[ 2.3591003   3.924478    1.9957986   1.5840237 ]
  [ 2.1052017   1.6462998   2.8093176   2.3065953 ]
  [ 3.0374813   2.8344321   1.8001952   1.1931461 ]]

 [[ 3.2624083   2.5387187   2.9646502   3.8290107 ]
  [ 1.8132234  -0.25027943  2.8257606   0.35598338]
  [ 2.1425831   1.4351314   1.5402347   2.1957223 ]]], shape=(2, 3, 4), dtype=float32)


<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[2.3591003 , 3.924478  , 1.9957986 , 1.5840237 ],
        [2.1052017 , 1.6462998 , 2.8093176 , 2.3065953 ],
        [3.0374813 , 2.8344321 , 1.8001952 , 1.1931461 ]],

       [[3.2624083 , 2.5387187 , 2.9646502 , 3.8290107 ],
        [1.8132234 , 0.25027943, 2.8257606 , 0.35598338],
        [2.1425831 , 1.4351314 , 1.5402347 , 2.1957223 ]]], dtype=float32)>

In [17]:
print(tf.math.reciprocal(ten))

tf.Tensor(
[[[ 0.29336035  0.5578805   0.62417924  1.2503881 ]
  [ 0.26665118  0.5652544   0.4913369   0.50584984]
  [ 0.7948487   0.3800255   0.5147251   0.6135957 ]]

 [[ 0.47145995  0.35565004  0.46378535  2.0817213 ]
  [ 0.80598664  0.7818586   0.3446374   0.36546418]
  [ 0.43164983 -9.231357    0.3618721   1.3283731 ]]], shape=(2, 3, 4), dtype=float32)


In [19]:
print(ten)
print(tf.round(ten))
print(tf.sign(ten))

tf.Tensor(
[[[ 3.4087768   1.7924985   1.602104    0.79975164]
  [ 3.750218    1.769115    2.0352633   1.9768713 ]
  [ 1.2581011   2.6314023   1.9427845   1.6297376 ]]

 [[ 2.1210709   2.8117528   2.15617     0.4803717 ]
  [ 1.2407154   1.2790036   2.9016004   2.7362463 ]
  [ 2.3166926  -0.10832644  2.7634072   0.7528006 ]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[[ 3.  2.  2.  1.]
  [ 4.  2.  2.  2.]
  [ 1.  3.  2.  2.]]

 [[ 2.  3.  2.  0.]
  [ 1.  1.  3.  3.]
  [ 2. -0.  3.  1.]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1. -1.  1.  1.]]], shape=(2, 3, 4), dtype=float32)


In [31]:
print(ten)
print(tf.argmax(ten,axis=13))
print(tf.argmin(ten,axis=0))

tf.Tensor(
[[[ 3.4087768   1.7924985   1.602104    0.79975164]
  [ 3.750218    1.769115    2.0352633   1.9768713 ]
  [ 1.2581011   2.6314023   1.9427845   1.6297376 ]]

 [[ 2.1210709   2.8117528   2.15617     0.4803717 ]
  [ 1.2407154   1.2790036   2.9016004   2.7362463 ]
  [ 2.3166926  -0.10832644  2.7634072   0.7528006 ]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[1 2 1 1]
 [2 0 1 1]], shape=(2, 4), dtype=int64)
tf.Tensor(
[[1 0 0 1]
 [1 1 0 0]
 [0 1 0 1]], shape=(3, 4), dtype=int64)
